name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Run Juice Shop Application
      run: |
        npm install
        npm start &
        sleep 30 # Wait for the app to start

    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.4.0
      with:
        target: 'http://localhost:3000' # Change to your application URL
        rules_file_name: '.zap/rules.tsv' # Optional: Specify custom rules
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
